### ISSUE TITLE
Feature request - A way to manually update the header

### ISSUE THREAD

**Issue by gvgramazio** [HugoOM/sfdx_autoheader#19]
Currently with the corresponding setting enabled, when I save a class the header is generated if not present and updated if already present. If I disable this setting there is a command that provides the generation of the header but there is none to update it. 

Could you please add this new command or integrate it with the already existing one?

**Comment by HugoOM** [comment]
Hi @gvgramazio,

That is a very good suggestion! 

In a future update, I'll try to make it part of the same manual command that already exists for manual insertion so that it updates it instead if a header is present on the file. 

I'll also update the label and documentation for said command so that this new behavior is clear. 

Thanks

**Comment by HugoOM** [comment]
Hi! 

#35 now changed the behavior of File Header update so that if one is detected on the current file upon saving, it will always be updated regardless of the "EnabledForApex" setting. 

Hopefully that addresses this issue properly. 

Thanks again for the feedback!
